import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";

// 定义字体inter
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App", // 页面标题，显示在浏览器标签上
    description: "Generated by create next app",  // 页面描述，通常用于SEO
};

/* 根布局组件，接受一个children属性，类型为 React.ReactNode。Readonly<{}> 用于确保传入的 children 属性是只读的 */
export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    /*
    * 返回一个html页面
    * body 标签应用了 inter.className，用于将字体应用于整个页面。
    * children 被渲染在 body 标签内，这样可以确保所有子组件都继承和应用这些全局设置。
    *
    * 在React和Next.js中，className 相当于标准HTML中的 class 属性，
    * 但由于 class 是JavaScript中的保留字，所以在JSX语法中使用 className 代替。
    */
    return (
        <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
    );
}
